### ISSUE TITLE
Opening treetable item doesn't bind AJAX events to DOM nodes

### ISSUE THREAD

**Issue by dashorst** [wicketstuff/wicket1.5-tree#3]
Clicking on a TreeTableItem to open it and render its child nodes works partially: the child nodes are rendered, but the AJAX links' events are not bound to a Wicket handler.

See https://github.com/wicketstuff/wicket1.5-tree/blob/2616384c4333e9770b6671bc78d15edef72d0788/src/test/java/org/apache/wicket/extensions/markup/html/tree/TreeTablePageTest.java for a test case that illustrates this.

**Comment by duesenklipper** [comment]
Hi @dashorst, do you know anything about what might be causing this? I'm running into this problem at the moment (https://github.com/wicketstuff/core/issues/513) and in quite a bit of debugging I haven't figured it out yet.

**Comment by duesenklipper** [comment]
...I'm getting the feeling that the `AbstractTree$TreeItem#renderHead` is doing something wrong that causes the its children's header contributions to be ignored.

That said, I find that whole setup of TreeItem rendering its children (with renderHead, render, etc) very confusing.

**Comment by duesenklipper** [comment]
Found it.

`AbstractTree$TreeItem#renderHead` was originally what is now `renderHead(HtmlHeaderContainer)`. So for Wicket 7 it should have been converted to `internalRenderHead`, but instead got turned into `renderHead(IHeaderResponse)`. The effect is that the children's behavior's header items did not get rendered any more, because that is done by `internalRenderHead`.

I'm preparing a patch.
